### ISSUE TITLE
too verbose tests

### ISSUE THREAD

**Issue by jonassmedegaard** [kjetilk/p5-atteanx-query-cache#28]
On Debian we generally want to follow in build logs what is going on,
and for MakeMAker-based builds we therefore by defauly enable
TEST_VERBOSE=1.

For AtteanX::Query::Cache specifically, that causes build logs of more
than 50MB (I killed the build at that point).

Please consider lowering the amount of output when TEST_VERBOSE is
enabled - e.g. encapsulate extreme details under TEST_DEBUG=1.

**Comment by kjetilk** [comment]
ooops, yeah, I have had use for all that myself, but I'll fix it soon as I understand it is a problem.
