### ISSUE TITLE
parse_term_from_string is deprecated and will be removed in Attean 0.018

### ISSUE THREAD

**Issue by eserte** [kjetilk/p5-atteanx-query-cache#36]
Tests fail, probably because of this warning:

```
...
parse_term_from_string is deprecated and will be removed in Attean 0.018 (use parse_term_from_bytes instead) at /tmpfs/.cpan-build-cpansand/2016072309/AtteanX-Query-Cache-0.002-0/blib/lib/AtteanX/Query/AccessPlan/Cache.pm line 46.

#   Failed test 'no (unexpected) warnings (via done_testing)'
#   at t/simple-cache-planner.t line 178.
# Looks like you failed 1 test of 9.
t/simple-cache-planner.t ....... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
...
```

**Comment by kjetilk** [comment]
Ah, thanks! 

@kasei will this have any impact on how UTF8 strings are handled?

**Comment by kasei** [comment]
@kjetilk this is purely a change in the method name to make it more obvious what it's actually doing. So it shouldn't change anything. But be aware that the name is changing from a confusing one, so if you happened to be mis-using it before (based on the poor name), you'll still be mis-using it now.
