### ISSUE TITLE
Support Triple Pattern Fragments in the planner

### ISSUE THREAD

**Issue by kjetilk** [kjetilk/p5-atteanx-query-cache#5]

**Comment by kjetilk** [comment]
Depends on #24 which appears to be the final problem

**Comment by kjetilk** [comment]
Also depends on #15 since the planner gets really slow with all the plans LDF introduce.

**Comment by kasei** [comment]
At some point we can talk about improving performance by reducing the complexity of the planning. For example, you could reduce the batch size in the IDP planner, or switch to a purely greedy planning algorithm (which in your case might not actually reduce the quality of the produced plan).

**Comment by kjetilk** [comment]
Cool! It would be interesting to see if the current tests still pass with different planners, in which case I think we can just do it. :-)
