### ISSUE TITLE
Create a proxy server that runs the rest

### ISSUE THREAD

**Issue by kjetilk** [kjetilk/p5-atteanx-query-cache#7]

**Comment by kasei** [comment]
Will this proxy server be a SPARQL Protocol implementation that stands in between the client and the upstream endpoint? I've got some Attean-based endpoint code that I haven't committed yet that might be able to be re-purposed.

**Comment by kjetilk** [comment]
Yeah, that's the idea! Great if you have that code!

**Comment by kjetilk** [comment]
This needs kjetilk/p5-lwp-useragent-chicaching#4 for the actual retrieval
